---
title: "AMLHC-final-exam"
author: "Nico Hagmeier"
date: "2024-06-27"
output:
  pdf_document: default
  html_document: default
---
```{r}
# Laden der notwendigen Bibliotheken
library(randomForest)
library(caret)
library(e1071)
library(pROC)
library(ggplot2)
library(corrplot)
library(reshape2)
```

```{r}
diab <- read.csv("C:/Users/Scele/OneDrive/Desktop/AMLHC-final-exam/diabetes.csv", header = TRUE) 
str(diab)
head(diab)
summary(diab)

```
```{r}
print(colSums(is.na(diab)))
```
```{r}
ggplot(diab, aes(x = Outcome)) +
  geom_bar() +
  labs(x = "Outcome") +
  ggtitle("Count Plot for Outcome")
```
```{r}
ggplot(diab, aes(color = Outcome)) +
  geom_point(aes(x = Pregnancies, y = Glucose)) +
  geom_point(aes(x = Pregnancies, y = BloodPressure)) +
  geom_point(aes(x = Pregnancies, y = SkinThickness)) +
  geom_point(aes(x = Pregnancies, y = Insulin)) +
  geom_point(aes(x = Pregnancies, y = BMI)) +
  geom_point(aes(x = Pregnancies, y = DiabetesPedigreeFunction)) +
  geom_point(aes(x = Pregnancies, y = Age)) +
  facet_wrap(~Outcome) +
  ggtitle("Pairplot for Variables by Outcome")
```
```{r}
# Korrelationsmatrix berechnen
cor_matrix <- cor(diab[, sapply(diab, is.numeric)])

# Umwandlung der Korrelationsmatrix in ein langformatiges Dataframe
cor_matrix_melted <- melt(cor_matrix)

# Erstellen der Korrelationsmatrix-Heatmap
ggplot(cor_matrix_melted, aes(Var1, Var2, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#1a7ebd", mid = "white", high = "#fc8d59", midpoint = 0,
                       limits = c(-1, 1), name = "Correlation") +
  geom_text(aes(label = round(value, 2)), vjust = 1) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Correlation Heatmap",
       x = "Variables", y = "Variables") +
  coord_fixed()
```


```{r}
diab <- diab[!duplicated(diab), ]
```
```{r}
colSums(is.na(diab))
```
```{r}
print(sum(diab$BloodPressure == 0))
print(sum(diab$Glucose == 0))
print(sum(diab$SkinThickness == 0))
print(sum(diab$Insulin == 0))
print(sum(diab$BMI == 0))
```
```{r}
diab$Glucose[diab$Glucose == 0] <- mean(diab$Glucose[diab$Glucose != 0], na.rm = TRUE)
diab$BloodPressure[diab$BloodPressure == 0] <- mean(diab$BloodPressure[diab$BloodPressure != 0], na.rm = TRUE)
diab$SkinThickness[diab$SkinThickness == 0] <- median(diab$SkinThickness[diab$SkinThickness != 0], na.rm = TRUE)
diab$Insulin[diab$Insulin == 0] <- median(diab$Insulin[diab$Insulin != 0], na.rm = TRUE)
diab$BMI[diab$BMI == 0] <- median(diab$BMI[diab$BMI != 0], na.rm = TRUE)

```



```{r}
diab$Outcome <- as.factor(diab$Outcome)

```

```{r}
set.seed(123)  # Für Reproduzierbarkeit
trainIndex <- createDataPartition(diab$Outcome, p = 0.7, list = FALSE)
trainData <- diab[trainIndex, ]
testData <- diab[-trainIndex, ]

X_train <- trainData[, -ncol(trainData)]
y_train <- trainData$Outcome
X_test <- testData[, -ncol(testData)]
y_test <- testData$Outcome

```


```{r}
# Definieren des Modells und der Parameter
model <- trainControl(method = "repeatedcv", number = 10, repeats = 3, search = "grid")
tunegrid <- expand.grid(.mtry = c(sqrt(ncol(X_train)), log2(ncol(X_train))))
```
```{r}
# Durchführung der Grid-Suche
set.seed(1)
rf_gridsearch <- train(X_train, y_train, method = "rf", metric = "Accuracy", tuneGrid = tunegrid, trControl = model, ntree = 1800)

# Beste Parameter finden
best_model <- rf_gridsearch$finalModel
print(rf_gridsearch)

```
```{r}
# Vorhersagen mit dem besten Modell
rf_pred <- predict(rf_gridsearch, X_test)
```
```{r}
# Klassifikationsbericht ausdrucken
conf_matrix <- confusionMatrix(rf_pred, y_test)
print(conf_matrix)

precision <- posPredValue(rf_pred, y_test, positive = "1")
recall <- sensitivity(rf_pred, y_test, positive = "1")
f1 <- 2 * (precision * recall) / (precision + recall)

cat("\nPrecision:\n", precision)
cat("\nRecall:\n", recall)
cat("\nF1-Score:\n", f1)

```

```{r}
# Konfusionsmatrix als Heatmap darstellen
conf_matrix_table <- as.table(conf_matrix$table)
ggplot(data = as.data.frame(conf_matrix_table), aes(x = Reference, y = Prediction, fill = Freq)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "red") +
  theme_minimal() +
  labs(title = "Confusion Matrix Heatmap", x = "Actual", y = "Predicted")
```



